QUERY_IS_NULL = 0
QUERY_IS_EMPTY = 1

WRONG_ATTRIBUTE_PROVIDED = 2
WRONG_KEYWORD_TYPE = 3
UNRECOGNIZED_OPERATOR = 4
TOKENS_IS_EMPTY = 5

INCORRECT_GRAMMAR = 6
MISSING_LEFT_PARENTHESIS = 7
MISSING_RIGHT_PARENTHESIS = 8
MISSING_KEYWORD = 9
MISSING_OPERAND = 10
MISSING_BINDER = 11
MISSING_IDENTIFIER = 12
MISSING_LEFT_SQUARE_BRACKET = 13
MISSING_RIGHT_SQUARE_BRACKET = 14
MISSING_ATTRIBUTE = 15


class DslSyntaxError(Exception):
    pass
